### ISSUE TITLE
Main.java

### ISSUE THREAD

**Issue by d-frolov** [SiiTP/Java_Frontend#2]
```
    int port = PORT;
    if (args.length == 1) {
        String portString = args[0];
        port = Integer.parseInt(portString);
    }
```

Не очень хорошая идея в случае некорректных входных параметров молча запускаться с настройками по-умолчанию

**Comment by Ivanbmstu** [comment]
Исправил.
В случае, когда сервер пытаются запустить с текстом в аргументах, то он не запускается. 
В случае, если аргументы 0 или меньше 0, то сервер не запускается.
